// <auto-generated />
using ComicManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicManager.Migrations
{
    [DbContext(typeof(ComicManagerContext))]
    [Migration("20181209190756_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicManager.Data.Entities.Comic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cover_date");

                    b.Property<string>("date_added");

                    b.Property<string>("date_aquired");

                    b.Property<string>("date_last_updated");

                    b.Property<string>("description");

                    b.Property<string>("issue_number");

                    b.Property<string>("name");

                    b.Property<string>("price_paid");

                    b.Property<string>("thumb_nail_url");

                    b.Property<string>("volume_name");

                    b.HasKey("id");

                    b.ToTable("Comics");

                    b.HasData(
                        new { id = 1, date_aquired = "12/9/2018 7:07 PM", issue_number = "1", name = "Sample Comic", thumb_nail_url = "xxx", volume_name = "Sample Volume" },
                        new { id = 2, date_aquired = "12/9/2018 7:07 PM", issue_number = "2", name = "Sample Comic", thumb_nail_url = "xxx", volume_name = "Sample Volume" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
